trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      docker login -u $(registryName) -p $(registryPassword) $(registryUrl)
      docker build . -t $(registryUrl)/eshoponweb:$(Build.BuildId) 
      docker tag $(registryUrl)/eshoponweb:$(Build.BuildId) $(registryUrl)/eshoponweb:latest
      docker push $(registryUrl)/eshoponweb
