trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubSync

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |     
      git remote add --mirror=fetch dsttmp "https://$(GitHubPAT)@github.com/$(GitHubOrg)/$(GitHubRepo)"
      git push dsttmp --progress --prune +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
